const webProjects = [
  {
    title: "COVID | Headline",
    year: "2020",
    identifier: "covid-headline-2020",
    tags: ["HTML", "CSS", "JavaScript", "React.js", "REST API"],
    priority: 4.5,
    detailViewType: "iframe",
    iframeUrl: "https://zhumingcheng697.github.io/dynamic-web-midterm/",
    sourceUrl: "https://github.com/zhumingcheng697/dynamic-web-midterm",
    descriptions: [
      'COVID | Headline is the midterm project for my <i>Dynamic Web Applications</i> class that I built using React.',
      'The website displays the current COVID-19 statistics along side the top news headlines in a given country or region using two RESTful APIS.',
      'It will display the statistics and headlines in the estimated user location based on their IP address if they don&rsquo;t specify a location, or if no useful data can be found for the location they specified.',
      'It automatically loads more headlines when users scroll to the end of the page and automatically refreshes the COVID-19 statistics every 15 minutes in the background.',
      'I also optimized the website for devices with screen insets (also known as notches) and included support for light mode and dark mode.',
      'The headline API would not work on publicly deployed sites due to API plan constraints, but I was able to deploy a simple back end in 2022 and circumvent the restriction.'
    ]
  },
  {
    title: "Rate My Classes",
    year: "2020",
    identifier: "rate-my-classes-2020",
    tags: ["HTML", "CSS", "JavaScript", "Node.js", "React.js", "Express.js", "REST API", "Web Scraping", "Firebase"],
    priority: 5,
    detailViewType: "iframe",
    iframeUrl: "https://rate-my-classes.netlify.app/",
    sourceUrl: "https://github.com/zhumingcheng697/dynamic-web-final",
    descriptions: [
      'Rate My Classes is the final project for my <i>Dynamic Web Applications</i> class that I built using Firebase, Express, React, and Node.js.',
      'The website allows students to post and review class information and ratings.',
      'It includes accounts and password authentication functionalities to allow users to keep track of all their reviews in one place and users can edit or remove their previous reviews with ease.',
      'The puppeteer headless browser is also used in the <a target="_blank" rel="noreferrer" href="https://stark-basin-35300.herokuapp.com/">back end</a> as a web scraper to obtain details of the classes such as department information, offered schedule, descriptions, and number of credits.'
    ]
  },
  {
    title: "OurScheduler",
    year: "2021",
    identifier: "our-scheduler-2021",
    tags: ["HTML", "CSS", "JavaScript", "TypeScript", "Node.js", "Vue.js", "Express.js", "D3.js", "REST API", "Web Scraping", "MongoDB"],
    priority: 5,
    detailViewType: "iframe",
    iframeUrl: "https://ourscheduler.netlify.app/",
    sourceUrl: "https://github.com/zhumingcheng697/OurScheduler",
    descriptions: [
      'OurScheduler is a powerful college course scheduler that my team built during <a target="_blank" rel="noreferrer" href="https://pennapps-xxii.devpost.com">PennApps XXII</a> and was awarded the Best Education Hack and ranked Top 9.',
      'It allows college students across universities to choose a large amount of classes they are considering taking, lock some classes as &ldquo;must haves&rdquo;, choose the total number of credits and/or classes they want to take, and let the algorithm automatically generate multiple schedules for them that fit their needs.',
      'Different from traditional schedulers that force users to input the hours of the classes they want to take by hand or manually remove a class to add another a class that has a conflicting schedule, OurScheduler does everything automatically.',
      'The website is built using MongoDB, Express, Vue, Node.js, and TypeScript. The puppeteer headless browser is also used as a web scraper to obtain the schedule of the courses, and the generated schedule is visualized using D3.js on the front end.',
      'At the hackathon, I was responsible for the entire Vue front end and I incorporated the database and schedule generation algorithms my teammates wrote into an Express back end with the scraper I built.',
      'After the hackathon was over, I continued to work on this project. On the front end, I added support for dark mode, redesigned the visualization of the schedule, and allowed users to switch through all the tentative schedules generated by the algorithm, and I improved the efficiency and reliability of the schedule generation algorithm by up to 5 times on the back end.',
      'A few months later, I also refactored both the front end and back end to TypeScript from JavaScript to improve code robustness, improved the accessibility to allow keyboard-only control on the front end, and modified the back end algorithm so that the scraper will automatically load new class information if what is in the database is outdated.'
    ]
  },
  {
    title: "Chat Room Pro",
    year: "2022",
    identifier: "chat-room-pro-2022",
    tags: ["HTML", "CSS", "JavaScript", "Node.js", "WebSocket", "Media Capture"],
    priority: 5,
    detailViewType: "iframe",
    iframeUrl: "https://zhumingcheng697.github.io/Live-Web/chat-room-pro",
    sourceUrl: "https://github.com/zhumingcheng697/Live-Web/tree/main/chat-room-pro",
    descriptions: [
      'Chat Room Pro is the midterm project for my <i>Live Web</i> class.',
      'It is a safe, powerful, and anonymous chat room for people to meet with others from all over the world.',
      'Users can choose a randomized username before they join, but they can also come up with one themselves. No additional signup process is needed.',
      'Not only can users send regular text messages or take a picture using their camera of choice (if there are more than one camera available on the device), users can also unsend previous messages and report inappropriate messages.',
      'A robust system is implemented to prevent users from spamming or sending multiple inappropriate messages.',
      'Current status of all users is kept track of so users can easily know how many people there are in the room, when they last joined, and whether they are still active to estimate if or when they might hear back and also to prevent cyber stalking.',
    ]
  }
];
